### ISSUE TITLE
能不能在github action里面使用的时候,直接下载可执行文件,而不是重新编译一次,编译xmake时间都要3分钟了?

### ISSUE THREAD

**Issue by masx200** [xmake-io/github-action-setup-xmake#22]
### 你在什么场景下需要该功能？

能不能在github action里面使用的时候,直接下载可执行文件,而不是重新编译一次,编译xmake时间都要3分钟了?

### 描述可能的解决方案

能不能在github action里面使用的时候,直接下载可执行文件,而不是重新编译一次,编译xmake时间都要3分钟了?

### 描述你认为的候选方案

能不能在github action里面使用的时候,直接下载可执行文件,而不是重新编译一次,编译xmake时间都要3分钟了?

### 其他信息
```
            - uses: xmake-io/github-action-setup-xmake@v1
              with:
                  xmake-version: latest
```

**Comment by waruqi** [comment]
see https://github.com/xmake-io/github-action-setup-xmake/issues/16

**Comment by OpportunityLiu** [comment]
其实可以考虑，github 环境也就那么几个，编译好放release里直接下载就行了

现在那个cache不是个好的解决方案

**Comment by waruqi** [comment]
> 其实可以考虑，github 环境也就那么几个，编译好放release里直接下载就行了
> 
> 现在那个cache不是个好的解决方案

放 release 还不如这个 cache，windows 上现在就是自动上传 release。用到现在 很多问题，要是有时间，我都想把 windows 上 dev 上传 release 那部分给删了，全走源码编译。

1. 更新不及时，我 xmake 改完，要等 xmake 的 ci 跑完，至少 30min 后才能更新上去，期间还不能改代码，否则重新触发 ci ，又得等一遍，如果 ci 跪了，还得再等。。就像 xmake-repo 现在用的就是 dev 。windows 版本更新修复和测试一个周期太长，严重影响效率。如果单独再搞个 ci 跳过 tests 部分，又是一堆 ci job ，太占资源，也不方便维护。

2. 经常遇到上传 release 失败，导致 binary 在 release 上都是经常没了，xmake-repo ci上跑任务，经常遇到 安装 xmake 404 跪了。。

3. 如果不算 dev ，仅仅 发布版本上传 release 那就更没必要了，走现在的 cache 也仅仅跑一次，就永久 cache 了。。没必要放一堆文件到 release。。

现在 release 上太多东西，我已经删掉一些没用的，比如 deb 包，之前就是 ci build 完上传到 release，但是这个包太依赖 ci 环境，反而给用户误导，他们自己下载下来装 debian/ubuntu 上，各种报错，各种 issues 给我。。

ci build的很多只能给 ci 自己用，但是用户不知道，看到 release 上一坨文件，更不知道到底用哪个包安装了。。更乱

**Comment by masx200** [comment]
上传release可以用github action来解决

**Comment by waruqi** [comment]
> 上传release可以用github action来解决

我刚说的 windows 上传的 release 问题。。就是 action 上传的。。一堆问题

**Comment by waruqi** [comment]
而且即使上传 release 成功，但是上传过程中，也有个空挡 时间差，在上传覆盖之前release文件的过程中，会有一小段时间 无法下载，导致我这其他从 release 下载安装 window xmake release 的 ci job 跑跪，也是经常遇到。。每次都要重跑下才行。。

**Comment by masx200** [comment]
可以搞个nightly分支

**Comment by waruqi** [comment]
> 可以搞个nightly分支

不搞，没本质区别。而且维护不过来这么多分支。。

**Comment by OpportunityLiu** [comment]
传肯定是传到这个repo的release里，只给actions用

我现在不确定的就是需要准备多少版本，一个版本准备 win/mac/linux 够不够

**Comment by waruqi** [comment]
> 传肯定是传到这个repo的release里，只给actions用
> 
> 我现在不确定的就是需要准备多少版本，一个版本准备 win/mac/linux 够不够

刚说了，如果是线上版本，那现在 cache 方式基本够用了，一次 build ，长时间缓存。。跟上传这里 release 没有太大区别，还更容易维护。。

如果是用 dev/master 等分支版本，上传 release 问题更多，还不如每次 build 。。而且 cache 支持 dev 分支 cache，只有新 commit ，才会刷 cache，不是每次 build，也基本够用。。

**Comment by OpportunityLiu** [comment]
@masx200 你那面是什么情况啊？现在的cache没生效吗？

**Comment by masx200** [comment]
> @masx200 你那面是什么情况啊？现在的cache没生效吗？

我这里没什么问题,之前忘记加缓存了

**Comment by OpportunityLiu** [comment]
。。。

**Comment by waruqi** [comment]
> 要用最新版本也可以给每个commit都生成一个持续集成的release版本，自动化完成很好用的

刚不是说了么，cache 原本就支持 commit cache。。上传 release 问题多。。
