### ISSUE TITLE
windows版本也可以用Sha builds和PR builds,通过只更新lua脚本的方式,也可以缓存.

### ISSUE THREAD

**Issue by masx200** [xmake-io/github-action-setup-xmake#23]
### 你在什么场景下需要该功能？

windows版本也可以用Sha builds和PR builds,通过只更新lua脚本的方式,也可以缓存.

### 描述可能的解决方案

可先下载一个最新版的安装程序安装上,然后通过只更新lua脚本的方式.

windows版本也可以用Sha builds和PR builds,,也可以缓存.

### 描述你认为的候选方案

或者使用`xmake update -s `的方式更新到指定的版本

**Comment by waruqi** [comment]
done
