### ISSUE TITLE
Should upgrade to a newer version of Node.js

### ISSUE THREAD

**Issue by futrime** [xmake-io/github-action-setup-xmake#28]
### Is your feature request related to a problem? Please describe.

In GitHub Actions summary, there is a warning message showing the deprecation of Node.js 16:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: xmake-io/github-action-setup-xmake@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

### Describe the solution you'd like

Upgrade to Node.js 18 or 20.

**Comment by waruqi** [comment]
you can open a pr to upgrade it.

**Comment by futrime** [comment]
OK
