### ISSUE TITLE
github  action 上 MSVC 编译失败

### ISSUE THREAD

**Issue by PeakRacing** [xmake-io/github-action-setup-xmake#32]
### Xmake 版本

2.9.2

### 操作系统版本和架构

win11

### 描述问题

在 ilammy/msvc-dev-cmd 提过此问题，作者认为可能是xmake问题
https://github.com/ilammy/msvc-dev-cmd/issues/82

特别说明下，之前有编译正常过

### 期待的结果

正常编译

### 工程配置

https://github.com/Dozingfiretruck/nes/blob/master/.github/workflows/windows.yml

### 附加信息和错误日志

https://private-user-images.githubusercontent.com/24759100/337827581-0785be6a-a288-4293-8e89-2edd35a93f11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNTc0MjcsIm5iZiI6MTcxODM1NzEyNywicGF0aCI6Ii8yNDc1OTEwMC8zMzc4Mjc1ODEtMDc4NWJlNmEtYTI4OC00MjkzLThlODktMmVkZDM1YTkzZjExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA5MjUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwNjQ5NDk4YTY2MTdmYzI5NDFiYWE1NzlmYWNhMDM5OTUxMDdmMmE2MTBmYWQwYmRhYTRlMjQ2M2JmODYyMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iA8VAKXmvL1SFUYMeXEudlvaROHfj5D3Gxk4E9CfaT4

**Comment by waruqi** [comment]
用 dev 版本。

```
uses: xmake-io/github-action-setup-xmake@v1
with:
  xmake-version: branch@dev
```

**Comment by PeakRacing** [comment]
> 用 dev 版本。
> 
> ```
> uses: xmake-io/github-action-setup-xmake@v1
> with:
>   xmake-version: branch@dev
> ```

可以了
