### ISSUE TITLE
github action 下载 xmake 需要 40 秒

### ISSUE THREAD

**Issue by pplmx** [xmake-io/github-action-setup-xmake#33]
### Xmake 版本

2.9.4

### 操作系统版本和架构

Github Action

### 描述问题

![image](https://github.com/user-attachments/assets/bb135b22-4eb2-4977-a61d-d1759a6a11c7)

### 期待的结果

快一点

### 工程配置

https://github.com/x-pt/example-cxx-xmake/blob/main/.github/workflows/ci.yml

### 附加信息和错误日志

无错误

**Comment by pplmx** [comment]
macOS 这边, 时间到达 1 分 20 秒

**Comment by waruqi** [comment]
需要编译安装，又不是直接拉二进制，快不了。

**Comment by pplmx** [comment]
> 需要编译安装，又不是直接拉二进制，快不了。

可以直接使用 xmake 的 release 么? 是存在什么问题么?

**Comment by waruqi** [comment]
linux 下这么多发行版，兼容性没保证。。不是一个 binary 就能解决的。。又不是 win

**Comment by pplmx** [comment]
OK，了解啦，Thanks♪(･ω･)ﾉ
