### ISSUE TITLE
xmake is always downloaded on Windows (not cached) despite actions-cache-folder

### ISSUE THREAD

**Issue by smac89** [xmake-io/github-action-setup-xmake#34]
### Xmake Version

2.9.6

### Operating System Version and Architecture

Windows-latest

### Describe Bug

I have a multi-build action which runs on both Linux and Windows. I notice that when this action runs on Windows, it always re-downloads `xmake`.

### Expected Behavior

The cached version should be used instead of downloading a new version.

### Project Configuration

```lua
```

### Additional Information and Error Logs

```console
```

**Comment by waruqi** [comment]
you can open a pr to support it.

**Comment by waruqi** [comment]
done
