### ISSUE TITLE
xmake-io must accept the GitHub Marketplace Developer Agreement. Contact an org admin to accept it.

### ISSUE THREAD

**Issue by OpportunityLiu** [xmake-io/github-action-setup-xmake#5]
> 注：如果是`问题报障`或者`特性请求`，请选择`报告缺陷`，`特性请求`模板，否则一律不回复。

### 描述讨论详情
请在这描述你需要讨论的话题详情。
![图片](https://user-images.githubusercontent.com/13471233/87748882-be4aaa00-c829-11ea-8e25-a11e864aac92.png)

@waruqi

**Comment by OpportunityLiu** [comment]
https://github.com/xmake-io/github-action-setup-xmake/releases/new

**Comment by waruqi** [comment]
![image](https://user-images.githubusercontent.com/151335/87749529-83497600-c82b-11ea-88f7-c12c13bfa8f7.png)

协议太长，我直接点了，你看能发了不？不会每次release都这么来一遍吧。。 = =

**Comment by OpportunityLiu** [comment]
org admin 应该现在只有你一个吧
https://github.com/orgs/xmake-io/people

**Comment by waruqi** [comment]
哦哦

**Comment by waruqi** [comment]
这个repo我单独给你加上admin了，应该可以修改写settings啥的。

**Comment by OpportunityLiu** [comment]
又出现了，同样的东西。。。

**Comment by waruqi** [comment]
？我都忘记了之前点哪 accept 了。Relase Action 这个在哪？Setting 里没找到。。

**Comment by waruqi** [comment]
找到了，点了下，你再试试呢

**Comment by OpportunityLiu** [comment]
又好了，这是一段时间就要来一次吗。。。

**Comment by waruqi** [comment]
> 又好了，这是一段时间就要来一次吗。。。

不知道哦，估计有过期时间吧 = =
